name: saemoi ci/cd - secret add
on:
  push:
    branches:
      - master
jobs:
  build:
    name: pull repo
    runs-on: ubuntu-latest
    steps:
    - name: git pull / install toast editor
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo su
          sudo chown -R ec2-user /home/ec2-user/saemoi
          cd saemoi
          sudo git pull
          npm i @toast-ui/react-editor --save --legacy-peer-deps 

    - name: npm run build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo su
          sudo chown -R ec2-user /home/ec2-user/saemoi
          cd saemoi
          npm i
          npm run build          
    
    - name: nginx, mysql restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo su
          sudo systemctl stop nginx
          sudo systemctl stop mysqld
          sudo systemctl start nginx
          sudo systemctl start mysqld
          
    - name: on pm2 server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo su
          sudo chown -R ec2-user /home/ec2-user/saemoi
          cd saemoi
          npx pm2 stop saemoi_server
          npx pm2 install typescript
          npx pm2 start server/saemoi_server.ts
